// Copyright (c) Tetrate, Inc 2020 All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: tsb/types/v2/options.proto

package extensions

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IstioObjectSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *IstioObjectSpec) Reset() {
	*x = IstioObjectSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tsb_types_v2_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioObjectSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioObjectSpec) ProtoMessage() {}

func (x *IstioObjectSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tsb_types_v2_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioObjectSpec.ProtoReflect.Descriptor instead.
func (*IstioObjectSpec) Descriptor() ([]byte, []int) {
	return file_tsb_types_v2_options_proto_rawDescGZIP(), []int{0}
}

func (x *IstioObjectSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var file_tsb_types_v2_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*IstioObjectSpec)(nil),
		Field:         2002,
		Name:          "tetrateio.api.tsb.types.v2.spec",
		Tag:           "bytes,2002,opt,name=spec",
		Filename:      "tsb/types/v2/options.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// optional tetrateio.api.tsb.types.v2.IstioObjectSpec spec = 2002;
	E_Spec = &file_tsb_types_v2_options_proto_extTypes[0]
)

var File_tsb_types_v2_options_proto protoreflect.FileDescriptor

var file_tsb_types_v2_options_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x73, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x74, 0x65,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x69, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x73, 0x62, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x49, 0x73,
	0x74, 0x69, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x3a, 0x60, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x74, 0x65, 0x74, 0x72, 0x61, 0x74, 0x65, 0x69, 0x6f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x73, 0x62, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x73,
	0x74, 0x69, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x65, 0x74, 0x72, 0x61, 0x74, 0x65, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x74, 0x73, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tsb_types_v2_options_proto_rawDescOnce sync.Once
	file_tsb_types_v2_options_proto_rawDescData = file_tsb_types_v2_options_proto_rawDesc
)

func file_tsb_types_v2_options_proto_rawDescGZIP() []byte {
	file_tsb_types_v2_options_proto_rawDescOnce.Do(func() {
		file_tsb_types_v2_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_tsb_types_v2_options_proto_rawDescData)
	})
	return file_tsb_types_v2_options_proto_rawDescData
}

var file_tsb_types_v2_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tsb_types_v2_options_proto_goTypes = []interface{}{
	(*IstioObjectSpec)(nil),          // 0: tetrateio.api.tsb.types.v2.IstioObjectSpec
	(*descriptor.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_tsb_types_v2_options_proto_depIdxs = []int32{
	1, // 0: tetrateio.api.tsb.types.v2.spec:extendee -> google.protobuf.MethodOptions
	0, // 1: tetrateio.api.tsb.types.v2.spec:type_name -> tetrateio.api.tsb.types.v2.IstioObjectSpec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tsb_types_v2_options_proto_init() }
func file_tsb_types_v2_options_proto_init() {
	if File_tsb_types_v2_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tsb_types_v2_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioObjectSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tsb_types_v2_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_tsb_types_v2_options_proto_goTypes,
		DependencyIndexes: file_tsb_types_v2_options_proto_depIdxs,
		MessageInfos:      file_tsb_types_v2_options_proto_msgTypes,
		ExtensionInfos:    file_tsb_types_v2_options_proto_extTypes,
	}.Build()
	File_tsb_types_v2_options_proto = out.File
	file_tsb_types_v2_options_proto_rawDesc = nil
	file_tsb_types_v2_options_proto_goTypes = nil
	file_tsb_types_v2_options_proto_depIdxs = nil
}
