// Copyright (c) Tetrate, Inc 2020 All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: tsb/rbac/v2/permissions.proto

package extensions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A permission defines an action that can be performed on a
// resource. By default access to resources is denied unless an
// explicit permission grants access to perform an operation against
// it.
type Permission int32

const (
	// Default value to designate no value was explicitly set for the permission.
	Permission_INVALID Permission = 0
	// The read permission grants read-only access to the resource.
	Permission_READ Permission = 1
	// The write permission allows the subject to modify an existing resource.
	Permission_WRITE Permission = 2
	// The create permission allows subjects to create child resources on the resource.
	Permission_CREATE Permission = 3
	// The delete permission grants permissions to delete the resource.
	Permission_DELETE Permission = 4
	// The set-iam permission allows subjects to manage the access policies for the resources.
	Permission_SET_POLICY Permission = 5
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "INVALID",
		1: "READ",
		2: "WRITE",
		3: "CREATE",
		4: "DELETE",
		5: "SET_POLICY",
	}
	Permission_value = map[string]int32{
		"INVALID":    0,
		"READ":       1,
		"WRITE":      2,
		"CREATE":     3,
		"DELETE":     4,
		"SET_POLICY": 5,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_tsb_rbac_v2_permissions_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_tsb_rbac_v2_permissions_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_tsb_rbac_v2_permissions_proto_rawDescGZIP(), []int{0}
}

var File_tsb_rbac_v2_permissions_proto protoreflect.FileDescriptor

var file_tsb_rbac_v2_permissions_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x73, 0x62, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x19, 0x74, 0x65, 0x74, 0x72, 0x61, 0x74, 0x65, 0x69, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x73, 0x62, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x32, 0x2a, 0x56, 0x0a, 0x0a, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59,
	0x10, 0x05, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x65, 0x74, 0x72, 0x61, 0x74, 0x65, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x73, 0x62, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tsb_rbac_v2_permissions_proto_rawDescOnce sync.Once
	file_tsb_rbac_v2_permissions_proto_rawDescData = file_tsb_rbac_v2_permissions_proto_rawDesc
)

func file_tsb_rbac_v2_permissions_proto_rawDescGZIP() []byte {
	file_tsb_rbac_v2_permissions_proto_rawDescOnce.Do(func() {
		file_tsb_rbac_v2_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_tsb_rbac_v2_permissions_proto_rawDescData)
	})
	return file_tsb_rbac_v2_permissions_proto_rawDescData
}

var file_tsb_rbac_v2_permissions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tsb_rbac_v2_permissions_proto_goTypes = []interface{}{
	(Permission)(0), // 0: tetrateio.api.tsb.rbac.v2.Permission
}
var file_tsb_rbac_v2_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tsb_rbac_v2_permissions_proto_init() }
func file_tsb_rbac_v2_permissions_proto_init() {
	if File_tsb_rbac_v2_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tsb_rbac_v2_permissions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tsb_rbac_v2_permissions_proto_goTypes,
		DependencyIndexes: file_tsb_rbac_v2_permissions_proto_depIdxs,
		EnumInfos:         file_tsb_rbac_v2_permissions_proto_enumTypes,
	}.Build()
	File_tsb_rbac_v2_permissions_proto = out.File
	file_tsb_rbac_v2_permissions_proto_rawDesc = nil
	file_tsb_rbac_v2_permissions_proto_goTypes = nil
	file_tsb_rbac_v2_permissions_proto_depIdxs = nil
}
